<div class="promo" data-mage-init='{"promoAnimations" : {}}'>
    <section class="promo__animated-section animated-section" data-section="animate-section">
        <div class="animated-section__container _container">
            <div class="animated-section__row _grid-2-cols">
                <div class="animated-section__images">
                    <div class="animated-section__image-placeholder animated-section__image-placeholder--iphone-front" data-animate-container="iphone-front" data-animate-pos="end"></div>
                    <div data-animate-container="iphone-back" data-animate-pos="start">
                        <div data-animate-component="iphone-back" data-animation-rules="translate scale fade-out" class="animated-section__image  ">
                            <img loading="lazy" src="<?php echo $this->getViewFileUrl('images/iphone-promo/iphone-back.png'); ?>" alt="iphone">
                        </div>
                    </div>
                    <div data-animate-container="iphone-front" data-animate-pos="start">
                        <div data-animate-component="iphone-front" data-animation-rules="translate-reverse" class="animated-section__image animated-section__image--second">
                            <img loading="lazy" src="<?php echo $this->getViewFileUrl('images/iphone-promo/iphone-front.png'); ?>" alt="iphone">
                        </div>
                    </div>

                </div>
                <div class="animated-section__content">
                    <div class="animated-section__logo">
                        <img loading="lazy" src="<?php echo $this->getViewFileUrl('images/iphone-promo/vodafone-logo.svg'); ?>" alt="iphone">
                    </div>
                    <h3 class="animated-section__title">Переходьте на iPhone SE</h3>
                    <h4 class="animated-section__sub-title">З Vodafone це сила</h4>
                    <div class="animated-section__labels promo-label">
                        <div class="promo-label__item">
                            <p class="promo-label__old-price">14 499 грн</p>
                            <p class="promo-label__final-price">11 499 грн</p>
                        </div>
                        <div class="promo-label__item promo-label__item--small">
                            <div class="promo-label__icon"></div>
                            <p class="promo-label__text">контракт на 12 мес</p>
                        </div>
                    </div>

                </div>

                <div class="animated-section__arrow">
                    <i></i>
                </div>
            </div>

            <div class="animated-section__row _grid-2-cols" data-animate-container="iphone-front-2" data-animate-pos="end">
                <div class="animated-section__content">
                    <div class="animated-section__icon">
                        <img src="" alt="">
                    </div>
                    <h3 class="animated-section__title">Найкраща камера</h3>
                    <p class="animated-section__text">Ширококутна камера 12 Мп з портретним режимом, портетним освітленням, функцією "Глибина", технологією Smart HRD нового поколыння ы пыдтримкою выдео 4К</p>
                </div>

                <div data-animate-container="iphone-back" data-animate-pos="end" class="animated-section__image-placeholder"></div>
            </div>

            <div class="animated-section__row _grid-2-cols">
                <div class="animated-section__images" >
                    <div data-animate-container="iphone-front-2" data-animate-pos="start" >
                        <div data-animate-component="iphone-front-2" data-animation-rules="translate fade-in" class="animated-section__image animated-section__image--iphone-front-2">
                            <img loading="lazy" src="<?php echo $this->getViewFileUrl('images/iphone-promo/iphone-front.png'); ?>" alt="iphone">
                        </div>
                    </div>
                </div>
                <div class="animated-section__content" >
                    <div class="animated-section__icon">
                        <i></i>
                    </div>
                    <h3 class="animated-section__title">HD Retina Дисплей</h3>
                    <p class="animated-section__text">Дисплей Retina HD 4.7" забезпечує яскраві і глибокі відчуття від перегляду зображення та відео</p>
                </div>
            </div>

            <div class="animated-section__row">
                <div class="animated-section__icon _animate">
                    <img src="" alt="">
                </div>
                <div class="animated-section__content">
                    <div class="animated-section__icon">
                        <i></i>
                    </div>
                    <h3 class="animated-section__title">
                        Потужний процесор BIONIC 13
                    </h3>
                    <p class="animated-section__text">
                        A13 Bionic - найшвидший та потужний процесор iPhone, з системою Neural Engine 3-го покоління. Забезпечує максимальну продустивність для додатків, ігор і фотозйомки
                    </p>
                </div>
            </div>
        </div>
    </section>

    <section class="promo__section promo-section">
        <div class="promo-section__container _container">
            <div class="promo-section__body">
                <h3 class="promo-section__title">Смотрите подробные характеристики</h3>
                <div class="promo-section__specifications product-specifications">
                    <div class="product-specifications__table specifications-table">
                        <h5 class="specifications-table__title"></h5>
                        <div class="specifications-table__item">
                            <div class="specifications-table__row">
                                <p>test</p>
                                <p>test</p>
                            </div>
                            <div class="specifications-table__row">
                                <p>test</p>
                                <p>test</p>
                            </div>
                        </div>
                        <h5 class="specifications-table__title"></h5>
                        <div class="specifications-table__item">
                            <div class="specifications-table__row">
                                <p>test</p>
                                <p>test</p>
                            </div>
                            <div class="specifications-table__row">
                                <p>test</p>
                                <p>test</p>
                            </div>
                            <div class="specifications-table__row">
                                <p>test</p>
                                <p>test</p>
                            </div>
                        </div>
                        <h5 class="specifications-table__title"></h5>
                        <div class="specifications-table__item">
                            <div class="specifications-table__row">
                                <p>test</p>
                                <p>test</p>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>
</div>