<div class="footer-promo">
    <div class="footer-promo__container">
        <div class="footer-promo__content">
            <div class="footer-promo__col">
                <div class="footer-promo__offer footer-offer">
                    <div class="footer-offer__header">
                        <div class="footer-offer__icon _icon">
                            <h3 class="footer-offet__title">Вигода 3000 грн</h3>

                        </div>
                    </div>
                    <div class="footer-offer__content">
                        <p>Що може бути краще за новий смартфон? Тільки новий смартфон зі знижками! Ловіть фіксовану знижку 3000 грн на крутезний смартфон iPhone SE 2020. Знижка надається за умови підключення контракту та оформлення страхового полісу "Смарт Ок" на 1 рік</p>
                    </div>
                </div>
            </div>
            <div class="footer-promo__col">
                <div class="footer-promo__offer footer-offer">
                    <div class="footer-offer__header">
                        <div class="footer-offer__icon _icon">
                            <h3 class="footer-offet__title">Спілкування
                                без меж</h3>

                        </div>
                    </div>
                    <div class="footer-offer__content">
                        <p>Отримуй максимум від тарифного плану та будь на зв'язку завжди! Підключай Vodafone Red XL на контрактній основі та насолоджуйся перевагами:
                            · Безліміт у мережі Vodafone Україна
                            · Безлімітний 4G/3G інтернет
                            · 350 хвилин на інші мережі
                            · 100 хв за кордон
                            · 350 SMS по Україні та за кордон</p>
                    </div>
                </div>
            </div>
            <div class="footer-promo__col">
                <div class="footer-promo__offer footer-offer">
                    <div class="footer-offer__header">
                        <div class="footer-offer__icon _icon">
                            <h3 class="footer-offet__title">Захисти свій смартфон на рік</h3>

                        </div>
                    </div>
                    <div class="footer-offer__content">
                        <p>Захисти смартфон — користуйся ним на повну!
                            Як часто у Вас падав смартфон? Або Ви випадково проливали на нього ранкову каву? Саме для того, щоб Ви могли користуватися своїм новеньким смартфоном на повну, забезпечте захист свого смартфону зі страховим продуктом «СмартОк». Вам потрібно лише оформити страховку і насолоджуватися усіма перевагами безпечного користування!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>